sudo: required

language: python

python:
  - 3.6

services:
  - docker

before_install:
  - docker-compose build

install:
  - pip install

script:
  - docker-compose run app test

after_success:
  - coveralls