dist: trusty
sudo: required

language: python
python: "3.6"

services:
  - postgres

addons:
  postgresql: "9.6"

script:
  - coverage run --source='.' manage.py test --settings=stuart_is.settings.test

after_success:
  - coveralls
