sudo: required

language: python

services:
  - docker

before_install:
  - docker-compose build

install:
  - pip install coveralls

script:
  - docker-compose run app test

after_success:
  - sed -i "s~/usr/src/coverage~$TRAVIS_BUILD_DIR~g" .coverage
  - cat .coverage
  - coveralls
