version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/application
    links:
      - db
      - redis
    ports:
      - 8000:8000
  db:
    image: "postgres:9.6.2"
    logging:
      driver: "none"
