version: 2
jobs:
  build:
    working_directory: ~/api.stuart.is
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    steps:
      - checkout
      - restore_cache:
          key: test-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Create virtualenv and install requirements
          command: |
            python3 -m venv test-venv
            . test-venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: test-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "test-venv"
      - run:
          name: Run tests and submit code coverage
          command: |
            . test-venv/bin/activate
            coverage run --source='.' manage.py test --settings=stuart_is.settings.test
            coveralls
  deploy:
    working_directory: ~/api.stuart.is
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          key: zappa-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/production.txt" }}
      - run:
          name: Create virtualenv and install requirements
          command: |
            python3 -m venv zappa-venv
            . zappa-venv/bin/activate
            pip install -r requirements/production.txt
      - save_cache:
          key: zappa-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/production.txt" }}
          paths:
            - "zappa-venv"
      - restore_cache:
          key: utils-{{ .Branch }}-{{ checksum "requirements/utils.txt" }}
      - run:
          name: Install AWS CLI
          command: |
            python3 -m venv utils-venv
            . utils-venv/bin/activate
            pip install awscli
      - save_cache:
          key: utils-{{ .Branch }}-{{ checksum "requirements/utils.txt" }}
          paths:
            - "utils-venv"
      - run:
          name: Prepare Zappa settings
          command: |
            . utils-venv/bin/activate
            aws s3 cp s3://$ZAPPA_SETTINGS_BUCKET/zappa_settings.yml .
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: feature/zappa
