version: 2
jobs:
  build:
    working_directory: ~/api.stuart.is
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    steps:
      - checkout
      - restore_cache:
          key: test-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/dev.txt" }}
      - run:
          command: |
            python3 -m venv test-venv
            . test-venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: test-{{ .Branch }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "test-venv"
      - run:
          command: |
            . test-venv/bin/activate
            coverage run --source='.' manage.py test --settings=stuart_is.settings.test
            coveralls
      - store_artifacts:
          path: test-reports/
          destination: tr1